Repository elastic/rally, pull requests merged in 2018-03, with the labels that each got.

#434 Remove Python faulthandler
  esrally/actor.py
  esrally/rally.py
Labels: :Internal, enhancement

#433 Add a unique race id
  docs/metrics.rst
  esrally/driver/driver.py
  esrally/metrics.py
  esrally/rally.py
  esrally/reporter.py
  esrally/resources/metrics-template.json
  esrally/resources/races-template.json
  esrally/resources/results-template.json
  tests/driver/driver_test.py
  tests/metrics_test.py
  tests/reporter_test.py
Labels: :Metrics, :Reporting, enhancement

#436 Bulk index all data by default
  esrally/driver/driver.py
  esrally/track/loader.py
  esrally/track/params.py
  esrally/track/track.py
  tests/driver/driver_test.py
Labels: :Usability, Review, enhancement

#437 Bump pytest* versions and beautify make test output
  setup.cfg
  setup.py
Labels: :Internal, enhancement

#438 Create legacy corpora only if needed
  esrally/track/loader.py
Labels: :Track Management, bug

#440 Use curl retry features to workaround transient network problems
  integration-test.sh
Labels: :Internal, enhancement

#441 Allow to pass parameters via a file
  docs/command_line_reference.rst
  esrally/rally.py
Labels: :Usability, enhancement

#451 Require java-10 to build Elasticsearch from source
  docs/configuration.rst
  esrally/config.py
  esrally/mechanic/supplier.py
  tests/config_test.py
  tests/mechanic/supplier_test.py
Labels: :Benchmark Candidate Management, :Config
