Repository elastic/rally, pull requests merged in 2018-10, with the labels that each got.

#583 Update ccr-stats telemetry device
  esrally/mechanic/telemetry.py
  tests/mechanic/telemetry_test.py
Labels: :Telemetry

#575 Always use remote branch for updates
  esrally/utils/repo.py
  tests/utils/repo_test.py
Labels: :Benchmark Candidate Management, :Track Management, bug

#586 Don't fail git clone is tty is not attached
  esrally/utils/git.py
  tests/utils/git_test.py
Labels: bug

#587 Fix typos and inconsistencies in help documentation
  esrally/rally.py
Labels: enhancement

#590 Update ccr-stats telemetry device
  esrally/mechanic/telemetry.py
  tests/mechanic/telemetry_test.py
Labels: :Telemetry
