Repository elastic/rally, pull requests merged in 2019-01, with the labels that each got.

#621 Minor typo
  README.rst
  docs/quickstart.rst
  docs/race.rst
  docs/summary_report.rst
  docs/tournament.rst
  docs/track.rst
  esrally/reporter.py
Labels: :Docs, enhancement

#622 Include NOTICE.txt in release
  .gitignore
  Makefile
  create-notice.sh
  release.sh
  scripts/offline-install.sh
  setup.py
Labels: :Internal, enhancement

#617 Fix conflicting pipelines and distribution version
  esrally/racecontrol.py
  tests/racecontrol_test.py
Labels: :Usability, enhancement

#625 Allow to specify a team revision
  docs/command_line_reference.rst
  esrally/mechanic/team.py
  esrally/rally.py
  esrally/utils/repo.py
  tests/utils/repo_test.py
Labels: :Benchmark Candidate Management, enhancement

#623 Update Developing Rally docs sections
  docs/developing.rst
  docs/install.rst
Labels: :Docs, enhancement

#627 Warn about skewed results when using node-stats telemetry device
  docs/telemetry.rst
  esrally/mechanic/telemetry.py
  tests/mechanic/telemetry_test.py
Labels: :Telemetry, enhancement

#630 Improve error message on missing repo directory
  esrally/utils/repo.py
  tests/utils/repo_test.py
Labels: :Benchmark Candidate Management, :Track Management, enhancement

#632 Update Release documentation for Rally
  RELEASE.md
Labels: :Docs, enhancement

#633 Ensure Makefile install target includes all release dependencies
  Makefile
Labels: :Internal, enhancement

#634 Fix typo
  esrally/rally.py
Labels: :Docs, enhancement

#638 Correct recorder-based sampling interval
  esrally/mechanic/telemetry.py
Labels: :Telemetry, bug

#637 Ignore JSON logs for merge parts analysis
  esrally/mechanic/telemetry.py
Labels: :Telemetry, enhancement
