Repository elastic/rally, pull requests merged in 2019-04, with the labels that each got.

#671 Add ability to download from S3 buckets
  create-notice.sh
  docs/track.rst
  esrally/utils/net.py
  setup.py
  tests/utils/net_test.py
Labels: :Benchmark Candidate Management, :Track Management, enhancement

#673 Honor runtime JDK in provisioner
  esrally/mechanic/java_resolver.py
  esrally/mechanic/launcher.py
  esrally/mechanic/provisioner.py
  tests/mechanic/provisioner_test.py
Labels: :Benchmark Candidate Management, bug

#668 Chart generator segment memory and new track combinations
  esrally/chart_generator.py
  esrally/rally.py
Labels: :Reporting, enhancement

#674 [Experimental] Capture peak usage of JVM mem pools
  esrally/mechanic/launcher.py
  esrally/mechanic/telemetry.py
  tests/mechanic/telemetry_test.py
Labels: :Telemetry, enhancement

#675 Fix chart generator segment memory bug
  esrally/chart_generator.py
Labels: :Internal, bug

#679 Skip Python install if already existing
  Makefile
Labels: :Internal, enhancement

#678 Upgrade Jinja to 2.10.1
  setup.py
Labels: :Internal, enhancement

#677 Allow shell redirects if possible
  esrally/utils/console.py
Labels: :Internal, enhancement

#676 Document ccr-stats telemetry device
  .gitignore
  docs/configuration.rst
  docs/recipes.rst
  docs/telemetry.rst
  esrally/mechanic/telemetry.py
  recipes/ccr/.elastic-version
  recipes/ccr/docker-compose.yml
  recipes/ccr/metricstore-docker-compose.yml
  recipes/ccr/start.sh
  recipes/ccr/stop.sh
  tests/mechanic/telemetry_test.py
Labels: :Docs, :Telemetry

#681 Use single node discovery type if suitable
  esrally/mechanic/provisioner.py
  tests/mechanic/provisioner_test.py
Labels: :Benchmark Candidate Management, enhancement

#682 Provide a platform-independent Rally binary
  scripts/offline-install.sh
Labels: :Internal, bug

#684 Use license instead of dist flavor in charts
  esrally/chart_generator.py
Labels: :Internal, bug

#683 Store mean for response-related metrics
  esrally/metrics.py
  esrally/reporter.py
  tests/metrics_test.py
  tests/reporter_test.py
Labels: :Metrics, enhancement

#687 Fix release charts after #684
  esrally/chart_generator.py
Labels: :Internal, bug

#686 Honor track-params in chart-generator
  esrally/chart_generator.py
Labels: :Internal, bug
