Repository elastic/rally, pull requests merged in 2019-07, with the labels that each got.

#716 Drop support for Elasticsearch 1.x
  docs/versions.rst
  esrally/driver/runner.py
  integration-test.sh
  tests/driver/runner_test.py
  tox.ini
Labels: :Load Driver, breaking, enhancement

#723 Always exit on OOME
  esrally/mechanic/provisioner.py
  tests/mechanic/provisioner_test.py
Labels: :Benchmark Candidate Management, :Internal, enhancement

#726 Don't check complete list of parameters in integration test
  integration-test.sh
Labels: :Internal

#728 Allow to set distribution version as parameter
  esrally/racecontrol.py
Labels: :Benchmark Candidate Management, enhancement

#729 Drop 1.x support for cluster metadata
  esrally/mechanic/telemetry.py
  tests/mechanic/telemetry_test.py
Labels: :Telemetry, breaking, enhancement

#730 Be resilient upon startup
  esrally/mechanic/launcher.py
  esrally/mechanic/mechanic.py
  esrally/mechanic/telemetry.py
  esrally/rally.py
  tests/mechanic/launcher_test.py
  tests/mechanic/telemetry_test.py
Labels: :Benchmark Candidate Management, enhancement

#735 Assume string type for params by default
  esrally/utils/opts.py
  tests/utils/opts_test.py
Labels: :Usability, enhancement

#720 Change filestore to be indexed by unique ID
  docs/docker.rst
  docs/migrate.rst
  docs/tournament.rst
  esrally/metrics.py
  esrally/paths.py
  esrally/rally.py
  esrally/reporter.py
  tests/metrics_test.py
Labels: :Benchmark Candidate Management, enhancement

#731 Update DiskIo telemetry device to persist the counters
  esrally/mechanic/launcher.py
  esrally/mechanic/telemetry.py
  tests/mechanic/telemetry_test.py
Labels: :Internal, :Telemetry, enhancement
