Repository elastic/rally, pull requests merged in 2019-08, with the labels that each got.

#739 Remove lap feature and all references.
  docs/command_line_reference.rst
  docs/metrics.rst
  docs/migrate.rst
  esrally/driver/driver.py
  esrally/mechanic/mechanic.py
  esrally/mechanic/telemetry.py
  esrally/metrics.py
  esrally/racecontrol.py
  esrally/rally.py
  esrally/reporter.py
  esrally/resources/metrics-template.json
  esrally/resources/races-template.json
  integration-test.sh
  tests/driver/driver_test.py
  tests/mechanic/telemetry_test.py
  tests/metrics_test.py
  tests/reporter_test.py
Labels: :Load Driver, :Metrics, :Reporting, breaking, enhancement

#748 Consistently render links to the documentation
  esrally/__init__.py
  esrally/client.py
  esrally/config.py
  esrally/racecontrol.py
  esrally/rally.py
  esrally/rallyd.py
  tests/client_test.py
  tests/racecontrol_test.py
Labels: :Internal, enhancement

#737 Allow to attach telemetry devices without reprovisioning
  esrally/mechanic/launcher.py
  esrally/mechanic/provisioner.py
  tests/mechanic/launcher_test.py
  tests/mechanic/provisioner_test.py
Labels: :Benchmark Candidate Management, :Internal, enhancement

#746 Fixup ProcessLauncherTests issues
  esrally/metrics.py
  tests/mechanic/launcher_test.py
Labels: :Internal, :Telemetry

#747 Log git output
  esrally/utils/git.py
  tests/utils/git_test.py
Labels: :Benchmark Candidate Management, :Track Management, bug

#750 Retrieve timestamped commit hash separately
  esrally/utils/git.py
  tests/utils/git_test.py
Labels: :Benchmark Candidate Management, :Track Management, bug

#725 Capture team and track revisions in metrics metadata
  esrally/mechanic/cluster.py
  esrally/mechanic/mechanic.py
  esrally/mechanic/team.py
  esrally/metrics.py
  esrally/racecontrol.py
  esrally/track/__init__.py
  esrally/track/loader.py
  esrally/utils/repo.py
  tests/metrics_test.py
  tests/utils/repo_test.py
Labels: :Metrics, enhancement

#755 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :Internal, enhancement

#751 Option track-revision should work with track-repository
  esrally/rally.py
  integration-test.sh
Labels: :Track Management, bug
