Repository elastic/rally, pull requests merged in 2019-06, with the labels that each got.

#703 Document known issues in dev setup
  docs/developing.rst
Labels: :Docs, enhancement

#700 Allow stdout print when running in Docker
  esrally/__init__.py
  esrally/racecontrol.py
  esrally/utils/console.py
  tests/racecontrol_test.py
  tests/utils/console_test.py
Labels: :Internal, enhancement

#705 Provide default for datastore.secure in all cases
  esrally/config.py
  tests/config_test.py
Labels: :Config, :Usability, enhancement

#704 Add download subcommand
  docs/command_line_reference.rst
  esrally/mechanic/__init__.py
  esrally/mechanic/mechanic.py
  esrally/rally.py
  esrally/utils/console.py
  integration-test.sh
  tests/utils/console_test.py
Labels: :Benchmark Candidate Management, enhancement

#702 Add Rally Docker image to release process
  Dockerfile
  Makefile
  RELEASE.md
  docker-compose.yml
  docker/Dockerfiles/Dockerfile-dev
  docker/Dockerfiles/Dockerfile-release
  docker/bin/entrypoint.sh
  docker/docker-compose-tests.yml
  docs/developing.rst
  docs/docker.rst
  docs/index.rst
  docs/install.rst
  integration-test.sh
  release-docker.sh
  release.sh
Labels: :Usability, enhancement, highlight

#706 Register pyenv Python versions
  Makefile
Labels: :Internal, bug

#707 Upgrade pip for virtualenv
  Makefile
Labels: :Internal, enhancement

#708 Align default request param extraction for queries
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: :Internal, enhancement

#709 Drop support for Python 3.4
  Makefile
  README.rst
  docs/developing.rst
  docs/install.rst
  docs/quickstart.rst
  esrally/__init__.py
  make-requirements.txt
  setup.py
  tox.ini
Labels: :Internal, breaking, enhancement

#710 Don't pass request_cache by default
  esrally/driver/runner.py
  esrally/track/params.py
  tests/driver/runner_test.py
  tests/track/params_test.py
Labels: :Load Driver, breaking, bug

#713 Check tags in track and team repos
  esrally/utils/git.py
  esrally/utils/repo.py
  tests/utils/git_test.py
  tests/utils/repo_test.py
Labels: :Benchmark Candidate Management, :Track Management, enhancement

#714 Document which ES versions are supported by Rally
  docs/command_line_reference.rst
  docs/index.rst
  docs/versions.rst
Labels: :Docs, enhancement

#701 Implement ES daemon-mode in process launcher
  esrally/mechanic/cluster.py
  esrally/mechanic/launcher.py
  esrally/mechanic/mechanic.py
  esrally/mechanic/provisioner.py
  esrally/mechanic/telemetry.py
  esrally/resources/docker-compose.yml.j2
  esrally/utils/sysstats.py
  tests/mechanic/launcher_test.py
  tests/mechanic/provisioner_test.py
  tests/mechanic/telemetry_test.py
Labels: :Benchmark Candidate Management, WiP, enhancement

#711 Change telemetry devices to rely on jvm.config instead of ES_JAVA_OPTS
  esrally/mechanic/launcher.py
  esrally/mechanic/provisioner.py
  esrally/mechanic/telemetry.py
  tests/mechanic/telemetry_test.py
Labels: :Benchmark Candidate Management, :Internal, enhancement
