Repository elastic/rally, pull requests merged in 2019-09, with the labels that each got.

#760 Improve logging of schedules
  esrally/driver/driver.py
Labels: :Load Driver, :Usability, enhancement

#758 Improve error message on SSL errors
  esrally/mechanic/launcher.py
  tests/mechanic/launcher_test.py
Labels: :Benchmark Candidate Management, :Usability, enhancement

#759 Show track and team revision when listing races
  esrally/metrics.py
Labels: :Reporting, enhancement

#762 Check that origin points to main repo for release
  release-checks.sh
Labels: :Internal, enhancement

#761 Allow to retry until success
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: :Load Driver, :Usability, enhancement

#764 Remove MergeParts internal telemetry device
  docs/metrics.rst
  docs/summary_report.rst
  esrally/mechanic/launcher.py
  esrally/mechanic/telemetry.py
  esrally/reporter.py
  tests/mechanic/telemetry_test.py
Labels: :Benchmark Candidate Management, :Telemetry, breaking

#727 Allow function-level invocation of integration-test.sh.
  integration-test.sh
  release-docker.sh
Labels: :Internal

#763 Run a task completely even without time-periods
  docs/adding_tracks.rst
  docs/migrate.rst
  esrally/driver/driver.py
  esrally/track/params.py
  tests/driver/driver_test.py
  tests/track/params_test.py
Labels: :Load Driver, bug

#766 Ensure tox environment is clean
  Makefile
Labels: :Internal, enhancement

#765 Start release process creating NOTICE
  release.sh
Labels: :Internal, enhancement

#767 Remove merge times from command line report
  esrally/reporter.py
Labels: :Reporting, enhancement

#768 Honor ingest-percentage for bulks
  esrally/track/params.py
  tests/track/params_test.py
Labels: :Load Driver, bug

#774 Raise an error if race is not found by id
  esrally/exceptions.py
  esrally/metrics.py
  tests/metrics_test.py
Labels: :Metrics, enhancement

#773 Store race files always as race.json
  esrally/metrics.py
  esrally/paths.py
  tests/metrics_test.py
Labels: :Metrics, enhancement

#775 Change NodeEnvironmentInfo from a telemetry device into a function.
  esrally/mechanic/launcher.py
  esrally/mechanic/telemetry.py
  tests/mechanic/telemetry_test.py
Labels: :Internal, :Metrics
