Repository elastic/rally, pull requests merged in 2019-11, with the labels that each got.

#803 Calculate system metrics per node
  docs/migrate.rst
  docs/summary_report.rst
  esrally/chart_generator.py
  esrally/driver/driver.py
  esrally/mechanic/mechanic.py
  esrally/metrics.py
  esrally/racecontrol.py
  esrally/reporter.py
  tests/driver/driver_test.py
  tests/mechanic/mechanic_test.py
  tests/metrics_test.py
  tests/reporter_test.py
Labels: :Metrics, :Reporting, enhancement

#810 Fix duplicated IP in distributed_load diagram
  docs/benchmark_distributed_load.gliffy
  docs/benchmark_distributed_load.png
Labels: :Docs, bug

#806 Upgrade jsonschema dependency
  setup.py
Labels: :Internal, cleanup

#807 Upgrade tabulate dependency
  setup.py
Labels: :Internal, cleanup

#815 Add Python 3.8 in Rally tests
  Makefile
  make-requirements.txt
  setup.py
  tox.ini
Labels: :Internal, enhancement

#817 Fix mistake in wait-for-recovery docs
  docs/track.rst
Labels: :Docs, bug

#819 Reduce API surface of loader
  esrally/track/__init__.py
Labels: :Internal, cleanup

#821 Move logrotate comments to separate lines
  docs/configuration.rst
  docs/migrate.rst
Labels: :Docs, enhancement

#818 Store build.log in log directory
  docs/configuration.rst
  docs/migrate.rst
  esrally/log.py
  esrally/mechanic/mechanic.py
  esrally/mechanic/supplier.py
  esrally/paths.py
  esrally/rally.py
  tests/mechanic/supplier_test.py
Labels: :Benchmark Candidate Management, breaking, enhancement

#820 Upgrade psutil to work with newer linux kernels
  setup.py
Labels: :Internal, bug

#814 Fix error handling for automatically derived version
  esrally/mechanic/mechanic.py
  esrally/racecontrol.py
Labels: :Benchmark Candidate Management, bug

#825 Change remaining it tests to port 19200
  docker/docker-compose-tests.yml
  integration-test.sh
Labels: :Internal, bug

#828 Remove auto-upgrade for old log config
  esrally/log.py
  esrally/rally.py
  esrally/rallyd.py
  esrally/resources/logging_1_0_0.json
Labels: :Internal, cleanup

#829 Reduce usage of platform-specific code
  esrally/config.py
  esrally/log.py
  esrally/rally.py
  esrally/resources/logging.json
  esrally/utils/console.py
  esrally/utils/git.py
  esrally/utils/io.py
Labels: :Internal, enhancement
