Repository elastic/rally, pull requests merged in 2020-09, with the labels that each got.

#1055 Check if total_transform_processing_times exist for compare reports
  esrally/reporter.py
Labels: :Reporting, bug, enhancement

#1057 Polling force merge
  docs/track.rst
  esrally/driver/runner.py
  esrally/resources/track-schema.json
  esrally/track/params.py
  tests/driver/runner_test.py
  tests/track/params_test.py
Labels: enhancement

#1059 Bump ES Client, Asyncio client and add pytest-asyncio
  setup.py
Labels: :Internal, enhancement

#1062 Document how to benchmark an Elastic Cloud cluster
  docs/recipes.rst
Labels: :Docs, enhancement

#1061 Pass JAVA15_HOME in build
  tox.ini
Labels: :Internal, enhancement

#1064 Fail fast if leading `/` is missing from `path` in raw-request
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: :Usability, enhancement
