Repository elastic/rally, pull requests merged in 2020-01, with the labels that each got.

#853 Allow to use the bundled JDK in Elasticsearch
  docs/command_line_reference.rst
  esrally/mechanic/java_resolver.py
  esrally/mechanic/launcher.py
  esrally/mechanic/provisioner.py
  esrally/mechanic/supplier.py
  esrally/rally.py
  tests/mechanic/java_resolver_test.py
  tests/mechanic/launcher_test.py
  tests/mechanic/provisioner_test.py
  tests/mechanic/supplier_test.py
Labels: :Benchmark Candidate Management, enhancement

#857 Disable all pylint checks that we want to fix
  .pylintrc
Labels: :Internal, cleanup

#858 Use the venv pylint in the makefile
  Makefile
Labels: :Internal, bug

#861 Pass plugin params for all plugins
  esrally/mechanic/team.py
  tests/mechanic/team_test.py
Labels: :Benchmark Candidate Management, bug

#862 Add support for excluded tasks in chart_generator
  esrally/chart_generator.py
Labels: :Internal, enhancement

#854 Fix lint issue C0303
  .pylintrc
  esrally/driver/scheduler.py
  esrally/mechanic/launcher.py
  esrally/mechanic/provisioner.py
  esrally/racecontrol.py
  esrally/rally.py
  esrally/utils/jvm.py
  tests/telemetry_test.py
  tests/track/loader_test.py
Labels: :Internal, cleanup

#859 Detach Elasticsearch on startup
  esrally/mechanic/launcher.py
  esrally/utils/process.py
Labels: :Benchmark Candidate Management, bug

#863 Allow piped stdin in run_subprocess_with_logging
  esrally/utils/process.py
Labels: :Internal, enhancement

#855 Fix lint issue C0301
  .pylintrc
  esrally/client.py
  esrally/driver/runner.py
  esrally/mechanic/provisioner.py
  esrally/metrics.py
  esrally/rally.py
  esrally/reporter.py
  esrally/telemetry.py
  esrally/track/__init__.py
  esrally/utils/io.py
  tests/client_test.py
  tests/driver/runner_test.py
  tests/mechanic/launcher_test.py
  tests/mechanic/supplier_test.py
  tests/racecontrol_test.py
  tests/telemetry_test.py
  tests/utils/opts_test.py
Labels: :Internal, cleanup

#864 Remove test step from precommit
  Makefile
Labels: :Internal, cleanup

#869 Fix W1201.
  .pylintrc
  esrally/mechanic/supplier.py
  esrally/track/params.py
Labels: cleanup

#871 Skip setup phase in IT tests during docker release
  integration-test.sh
Labels: :Internal

#860 More resilient node shutdown
  esrally/mechanic/launcher.py
  esrally/mechanic/mechanic.py
  tests/mechanic/launcher_test.py
Labels: :Benchmark Candidate Management, bug

#867 Fix W0143
  .pylintrc
  esrally/driver/runner.py
  esrally/track/track.py
Labels: cleanup

#868 Fix W0631
  .pylintrc
  esrally/chart_generator.py
  esrally/mechanic/team.py
Labels: bug

#872 Extend error msg to specify operation name for missing index
  esrally/driver/driver.py
  esrally/track/loader.py
  esrally/track/params.py
  tests/track/params_test.py
Labels: :Usability, enhancement

#876 Adjust IT tests for elastic/rally-eventdata-track#67
  tests/utils/opts_test.py
Labels: :Internal, cleanup

#873 Prevent installation with unsupported Python
  setup.py
Labels: :Usability, enhancement

#874 Store system metrics if race metadata are present
  esrally/mechanic/mechanic.py
Labels: :Benchmark Candidate Management, bug

#877 Don't write metrics to a closed metrics store
  esrally/mechanic/launcher.py
  esrally/mechanic/mechanic.py
Labels: :Benchmark Candidate Management, bug

#865 Updating force merge operation to force merge only track indices by default
  docs/track.rst
  esrally/driver/runner.py
  esrally/track/params.py
  tests/driver/runner_test.py
  tests/track/params_test.py
Labels: :Load Driver, enhancement

#879 Don't read from stdout/stderr on ES startup
  esrally/mechanic/launcher.py
  tests/mechanic/launcher_test.py
Labels: :Benchmark Candidate Management, enhancement

#880 Show recent log output on integration test failure
  integration-test.sh
Labels: :Internal, enhancement

#881 Wait for REST layer before version check
  esrally/client.py
  esrally/driver/driver.py
  esrally/mechanic/mechanic.py
  tests/client_test.py
  tests/driver/driver_test.py
Labels: :Benchmark Candidate Management, bug

#882 Make REST API check stricter
  esrally/client.py
  tests/client_test.py
Labels: :Load Driver, bug

#884 Detach ES using Python standard mechanism
  esrally/mechanic/launcher.py
Labels: :Benchmark Candidate Management, enhancement

#886 Fix race condition with old ES processes in IT tests
  integration-test.sh
Labels: :Internal, enhancement
