Repository elastic/rally, pull requests merged in 2020-04, with the labels that each got.

#943 Fix request timeout handling
  esrally/async_connection.py
  esrally/client.py
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: :Load Driver, bug

#937 Fix port number in recipes docs
  docs/recipes.rst
Labels: :Docs, :Usability, enhancement

#945 Add an override for the rally homedir
  it/__init__.py
  tox.ini
Labels: :Internal

#949 Upgrade Elasticsearch client to 7.6.0
  esrally/client.py
  setup.py
Labels: :Internal, enhancement

#944 Allow to use significantly more clients
  esrally/driver/driver.py
  esrally/metrics.py
  tests/driver/driver_test.py
Labels: :Load Driver, enhancement, highlight

#953 Pass JAVA14_HOME in build
  tox.ini
Labels: :Internal, enhancement

#947 Use pbzip2/pigz to decompress corpora if available
  docker/Dockerfiles/Dockerfile-dev
  docker/Dockerfiles/Dockerfile-release
  docs/install.rst
  esrally/utils/io.py
  tests/utils/io_test.py
Labels: :Usability, enhancement

#950 Add support for a RALLY_HOME env var everywhere
  esrally/config.py
  esrally/log.py
  esrally/paths.py
  integration-test.sh
  it/__init__.py
  tests/metrics_test.py
  tox.ini
Labels: :Internal, enhancement

#948 Align track reference structure with track
  docs/track.rst
Labels: :Docs, enhancement

#952 Allow to disable HTTP compression for all queries
  docs/track.rst
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: :Load Driver, enhancement

#951 Upgrade Thespian to 3.10.0
  setup.py
Labels: :Internal, enhancement

#955 Update docs to advise use of pbzip2 for new track corpus
  docs/adding_tracks.rst
Labels: :Docs, enhancement

#954 Add flag to handle running processes automatically
  docs/command_line_reference.rst
  esrally/rally.py
  esrally/utils/process.py
  tests/utils/process_test.py
Labels: :Usability, enhancement

#957 Move CI script to the rally repository
  .ci/build.sh
Labels: :Internal

#958 Avoid duplicate URL parsing for async connections
  esrally/async_connection.py
Labels: :Load Driver, enhancement

#956 Fix fallback implementation of ML-related runners
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: :Load Driver, bug

#960 Disable docstring linter check
  .pylintrc
Labels: :Internal, bug

#962 Increase bulk size to metrics store
  esrally/metrics.py
Labels: :Metrics, enhancement

#959 Clarify the impact on refreshes for node-stats telemetry
  docs/telemetry.rst
  esrally/telemetry.py
Labels: :Telemetry, enhancement

#964 Fix telemetry tests
  tests/telemetry_test.py
Labels: cleanup

#965 Always shutdown worker thread pool
  esrally/driver/driver.py
Labels: :Load Driver, bug

#961 Determine most recent sample per client
  esrally/driver/driver.py
Labels: :Load Driver, bug

#966 Migrate more integration tests
  integration-test.sh
  it/__init__.py
  it/distribution_test.py
  it/download_test.py
  it/info_test.py
Labels: :Internal, enhancement

#967 Raise an error when attempting to bulk-index without any corpora
  esrally/driver/runner.py
  esrally/track/params.py
  tests/track/params_test.py
Labels: :Track Management, :Usability, enhancement

#968 Add integration tests with eventdata
  it/__init__.py
  it/distribution_test.py
  it/list_test.py
Labels: :Internal, enhancement

#969 Add an it method for rally race
  it/__init__.py
  it/distribution_test.py
  it/sources_test.py
Labels: :Internal, enhancement

#963 Reduce mapped memory with many bulk clients
  esrally/driver/async_driver.py
  esrally/driver/driver.py
  esrally/track/params.py
  tests/driver/driver_test.py
  tests/track/params_test.py
Labels: :Load Driver, enhancement

#970 Add tooling to generate a track from existing data
  .gitignore
  Makefile
  docs/adding_tracks.rst
  docs/command_line_reference.rst
  esrally/rally.py
  esrally/resources/track.json.j2
  esrally/tracker/__init__.py
  esrally/tracker/corpus.py
  esrally/tracker/index.py
  esrally/tracker/tracker.py
  integration-test.sh
  it/tracker_test.py
  tests/tracker/__init__.py
  tests/tracker/corpus_test.py
  tests/tracker/index_test.py
Labels: :Track Management, enhancement, highlight

#974 Remove duplicate integration test
  integration-test.sh
Labels: :Internal, cleanup

#972 Pass actor system env vars in integration test
  tox.ini
Labels: :Internal, enhancement

#973 Remove warning about bogus results
  esrally/racecontrol.py
Labels: :Load Driver, cleanup

#971 Add thespian logs to ci
  .ci/build.sh
Labels: :Internal, enhancement

#977 Migrate track param check to new IT infrastructure
  integration-test.sh
  it/__init__.py
  it/info_test.py
Labels: :Internal, enhancement
