Repository elastic/rally, pull requests merged in 2020-07, with the labels that each got.

#1023 Migrate configure test to new IT infrastructure
  integration-test.sh
  it/__init__.py
  it/configuration_test.py
Labels: :Internal, enhancement

#1024 Allow runners to determine throughput
  esrally/driver/driver.py
  esrally/driver/runner.py
  tests/driver/driver_test.py
  tests/driver/runner_test.py
Labels: :Load Driver, enhancement

#1025 Upgrade to Thespian 3.10.1
  setup.py
Labels: :Internal, enhancement

#1027 Resolve JAVA_HOME for source builds lazily
  esrally/mechanic/supplier.py
  tests/mechanic/supplier_test.py
Labels: :Benchmark Candidate Management, bug

#1026 [WIP] Migrate first test_docker_dev_image
  integration-test.sh
  it/__init__.py
  it/docker_dev_image_test.py
Labels: :Internal, enhancement

#1022 add transform support
  docs/telemetry.rst
  docs/track.rst
  esrally/driver/driver.py
  esrally/driver/runner.py
  esrally/metrics.py
  esrally/reporter.py
  esrally/telemetry.py
  esrally/track/track.py
  tests/driver/runner_test.py
  tests/telemetry_test.py
Labels: :Load Driver, enhancement

#1028 Fetch artifact revision lazily on build
  esrally/mechanic/supplier.py
  tests/mechanic/supplier_test.py
Labels: :Benchmark Candidate Management, enhancement

#1030 Improve Python 3.8 compatibility
  setup.py
Labels: :Internal, cleanup

#1037 Correct Rally forum URL
  .github/ISSUE_TEMPLATE.md
  README.rst
  docs/configuration.rst
  docs/docker.rst
  docs/faq.rst
  docs/index.rst
  esrally/__init__.py
  esrally/config.py
  esrally/rally.py
Labels: :Docs, bug

#1041 Add indexing_pressure to nodes stats
  docs/telemetry.rst
  esrally/telemetry.py
  tests/telemetry_test.py
Labels: enhancement

#1029 Add integration test for proxy
  integration-test.sh
  it/__init__.py
  it/proxy_test.py
  it/resources/squid/squid.conf
  it/resources/squid/squidpasswords
  release-docker-test.sh
  release-docker.sh
  tox.ini
Labels: :Internal, enhancement

#1044 Improve support for benchmarks with many clients
  esrally/driver/driver.py
Labels: :Load Driver, bug
