Repository elastic/rally, pull requests merged in 2020-08, with the labels that each got.

#1038 Check for trailing comma tuple
  .pylintrc
  esrally/metrics.py
  esrally/track/params.py
Labels: :Internal, enhancement

#1039 Check for pointless statements
  .pylintrc
  esrally/mechanic/mechanic.py
  esrally/metrics.py
  esrally/utils/opts.py
  tests/mechanic/supplier_test.py
Labels: :Internal, enhancement

#1043 Installation and offline dist improvements
  RELEASE.md
  docs/install.rst
  release-checks.sh
  scripts/offline-install.sh
Labels: :Docs, :Packaging, bug

#1035 Warn on request errors
  esrally/metrics.py
  esrally/reporter.py
  tests/metrics_test.py
Labels: :Usability, enhancement

#1045 Show processing time also in comparison reports
  esrally/reporter.py
Labels: :Reporting, enhancement

#1031 Upgrade Elasticsearch client library to 7.8
  create-notice.sh
  esrally/async_connection.py
  esrally/client.py
  setup.py
Labels: :Internal, enhancement

#1047 Add runner to wait until snapshot has been created
  docs/track.rst
  esrally/driver/runner.py
  esrally/track/track.py
  tests/driver/runner_test.py
Labels: :Track Management, enhancement
