Repository elastic/rally, pull requests merged in 2020-10, with the labels that each got.

#1073 Fix pylint W0107
  .pylintrc
  esrally/actor.py
  esrally/driver/driver.py
  esrally/exceptions.py
  esrally/track/loader.py
Labels: cleanup

#1072 Fix pylint W0235
  .pylintrc
  esrally/driver/driver.py
  esrally/driver/runner.py
  tests/mechanic/mechanic_test.py
Labels: cleanup

#1075 Ensure that request error meta-data is string
  esrally/driver/driver.py
  tests/driver/driver_test.py
Labels: :Load Driver, bug

#1078 Upgrade pylint to 2.6.0
  .pylintrc
  esrally/driver/runner.py
  it/configuration_test.py
  it/docker_dev_image_test.py
  it/proxy_test.py
  setup.py
  tests/utils/io_test.py
Labels: cleanup

#1071 Fix parallel completed-by task identification
  esrally/track/loader.py
  tests/track/loader_test.py
Labels: :Track Management, bug

#1077 Avoid using exit() or quit()
  .pylintrc
  esrally/rally.py
  scripts/analyze.py
Labels: cleanup

#1088 Use the new pip dependency resolver
  Makefile
  docker/Dockerfiles/Dockerfile-dev
  docker/Dockerfiles/Dockerfile-release
  tox.ini
Labels: bug

#1089 Fix chart-generator
  esrally/chart_generator.py
Labels: :Internal, cleanup

#1082 Avoid assigning an expression to nothing
  .pylintrc
  esrally/reporter.py
  esrally/telemetry.py
Labels: cleanup

#1094 Add support for Google Cloud Storage buckets
  create-notice.sh
  docs/track.rst
  esrally/utils/net.py
  setup.py
  tests/utils/net_test.py
Labels: :Track Management, enhancement

#1079 Avoid invalid triple quotes
  .pylintrc
  esrally/__init__.py
  esrally/track/loader.py
  tests/track/loader_test.py
Labels: cleanup

#1081 Avoid using incorrect number of parameters
  .pylintrc
  esrally/driver/runner.py
  esrally/track/params.py
Labels: cleanup

#1076 Avoid defining and not using variables
  .pylintrc
  esrally/chart_generator.py
  esrally/config.py
  esrally/driver/driver.py
  esrally/driver/runner.py
  esrally/mechanic/mechanic.py
  esrally/mechanic/provisioner.py
  esrally/mechanic/supplier.py
  esrally/telemetry.py
  esrally/utils/io.py
  esrally/utils/net.py
  esrally/utils/process.py
  scripts/analyze.py
  tests/client_test.py
  tests/driver/driver_test.py
  tests/driver/scheduler_test.py
  tests/metrics_test.py
  tests/telemetry_test.py
  tests/time_test.py
  tests/track/params_test.py
Labels: cleanup

#1084 Avoid passing too few parameters into function calls
  .pylintrc
  esrally/driver/driver.py
  esrally/mechanic/mechanic.py
  esrally/racecontrol.py
  esrally/rally.py
  tests/metrics_test.py
Labels: cleanup

#1097 Upgrade google-auth to latest
  setup.py
Labels: :Internal, enhancement

#1092 Add Support for Datastreams
  esrally/driver/runner.py
  esrally/resources/track-schema.json
  esrally/track/loader.py
  esrally/track/params.py
  esrally/track/track.py
  tests/driver/runner_test.py
  tests/track/loader_test.py
  tests/track/params_test.py
  tests/track/track_test.py
Labels: :Load Driver, enhancement

#1065 Allow to specify corpus meta-data
  docs/track.rst
  esrally/resources/track-schema.json
  esrally/track/loader.py
  esrally/track/track.py
  tests/track/loader_test.py
  tests/track/track_test.py
Labels: :Track Management, enhancement

#1091 Check registered parameter sources more strictly
  esrally/track/params.py
  tests/track/params_test.py
Labels: :Track Management, enhancement
