Repository elastic/rally, pull requests merged in 2020-03, with the labels that each got.

#925 Allow to specify an indices stats condition
  docs/track.rst
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: :Load Driver, enhancement

#923 Assume a TTY for interactive commands
  esrally/actor.py
  esrally/rallyd.py
  esrally/utils/console.py
  tests/utils/console_test.py
Labels: :Usability, enhancement

#928 Don't invoke setup.py directly
  Makefile
  run.sh
Labels: :Internal, enhancement

#927 Add unit for all query charts
  esrally/chart_generator.py
Labels: bug

#929 Allow index-stats to compare non-existing path
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: :Load Driver, enhancement

#930 Update psutil to latest version
  setup.py
Labels: :Internal, enhancement

#905 Require at least Python 3.6
  .ci/variables.json
  Makefile
  docs/developing.rst
  docs/install.rst
  docs/quickstart.rst
  esrally/__init__.py
  setup.py
  tox.ini
Labels: breaking, cleanup

#916 Add an asyncio-based load generator
  create-notice.sh
  docs/adding_tracks.rst
  docs/migrate.rst
  esrally/async_connection.py
  esrally/client.py
  esrally/driver/__init__.py
  esrally/driver/async_driver.py
  esrally/driver/driver.py
  esrally/driver/runner.py
  esrally/racecontrol.py
  esrally/rally.py
  esrally/track/loader.py
  integration-test.sh
  setup.cfg
  setup.py
  tests/__init__.py
  tests/driver/async_driver_test.py
  tests/driver/driver_test.py
  tests/driver/runner_test.py
Labels: :Load Driver, enhancement, highlight

#931 Store Rally revision in metrics metadata
  esrally/metrics.py
  esrally/resources/races-template.json
  esrally/resources/results-template.json
  esrally/version.py
  tests/metrics_test.py
Labels: :Metrics, enhancement

#932 Improve layout of generated dashboards
  esrally/chart_generator.py
Labels: :Reporting, enhancement

#934 Bump minimum Python version to 3.8
  .ci/variables.json
  Makefile
  README.rst
  docker/Dockerfiles/Dockerfile-dev
  docker/Dockerfiles/Dockerfile-release
  docs/docker.rst
  docs/install.rst
  docs/migrate.rst
  docs/quickstart.rst
  esrally/__init__.py
  setup.py
  tox.ini
Labels: :Internal, breaking, enhancement

#919 Run integration tests with pytest
  Makefile
  integration-test.sh
  it/__init__.py
  it/list_test.py
  it/resources/rally-es-it.ini
  it/resources/rally-in-memory-it.ini
  it/sources_test.py
  setup.cfg
  setup.py
  tox.ini
Labels: :Internal, discuss, enhancement

#935 Add an asyncio-based load generator
  create-notice.sh
  docs/adding_tracks.rst
  docs/migrate.rst
  docs/track.rst
  esrally/async_connection.py
  esrally/client.py
  esrally/driver/__init__.py
  esrally/driver/async_driver.py
  esrally/driver/driver.py
  esrally/driver/runner.py
  esrally/metrics.py
  esrally/racecontrol.py
  esrally/rally.py
  esrally/reporter.py
  esrally/track/loader.py
  esrally/track/params.py
  esrally/utils/io.py
  integration-test.sh
  setup.cfg
  setup.py
  tests/__init__.py
  tests/driver/async_driver_test.py
  tests/driver/driver_test.py
  tests/driver/runner_test.py
  tests/track/params_test.py
Labels: :Load Driver, enhancement, highlight

#939 Correct JMC download link
  docs/telemetry.rst
Labels: :Docs, enhancement

#938 Store units in results
  esrally/metrics.py
  tests/metrics_test.py
Labels: :Metrics, enhancement

#941 Improve response processing
  docs/track.rst
  esrally/async_connection.py
  esrally/client.py
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: :Load Driver, enhancement

#942 Honor response-compression-enabled parameter
  esrally/track/params.py
  tests/track/params_test.py
Labels: :Load Driver, bug
