Repository elastic/rally, pull requests merged in 2021-03, with the labels that each got.

#1200 Add optional name in assertion message
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: :Load Driver, enhancement

#1201 Fix colour scheme and exclude tasks filters for charts
  esrally/chart_generator.py
Labels: :Internal

#1203 Log results of cluster health check
  esrally/driver/runner.py
Labels: :Usability, enhancement

#1199 Throttle requests from the beginning
  docs/migrate.rst
  esrally/driver/driver.py
Labels: :Load Driver, enhancement

#1208 Remove unreferenced code
  esrally/utils/io.py
  tests/utils/io_test.py
Labels: :Internal, cleanup

#1207 Expose an API to handle file offset tables
  esrally/utils/io.py
Labels: :Track Management, enhancement

#1212 Add searchable-snapshots-stats telemetry device
  docs/telemetry.rst
  esrally/driver/driver.py
  esrally/telemetry.py
  tests/telemetry_test.py
Labels: :Telemetry, enhancement

#1209 Ensure stable mappings for metrics
  esrally/resources/metrics-template.json
  esrally/resources/races-template.json
  esrally/resources/results-template.json
Labels: :Metrics, bug

#1213 Support chart_name filters in chart annotations
  esrally/chart_generator.py
Labels: :Internal, enhancement

#1216 Upgrade template engine
  setup.py
Labels: :Internal, enhancement

#1214 Collect metrics on composite subtasks
  docs/metrics.rst
  docs/migrate.rst
  esrally/client.py
  esrally/driver/driver.py
  esrally/driver/runner.py
  esrally/metrics.py
  tests/client_test.py
  tests/driver/driver_test.py
  tests/driver/runner_test.py
  tests/metrics_test.py
Labels: :Load Driver, enhancement

#1211 Add support for merge_count and merge_time graphs
  esrally/chart_generator.py
Labels: :Internal, enhancement

#1218 Fix chart-name filter for charts
  esrally/chart_generator.py
Labels: :Internal, bug

#1190 Add support for search_after and point-in-time
  .pylintrc
  benchmarks/driver/parsing_test.py
  docs/track.rst
  esrally/driver/runner.py
  esrally/track/params.py
  esrally/track/track.py
  setup.py
  tests/driver/runner_test.py
Labels: :Track Management, enhancement, highlight

#1217 Fix auto build of docs
  .ci/variables.json
  Makefile
  docs/conf.py
  it/installation_test.py
  tox.ini
Labels: bug

#1221 Store relative-time in milliseconds
  docs/metrics.rst
  docs/migrate.rst
  docs/recipes.rst
  esrally/metrics.py
  esrally/resources/metrics-template.json
  tests/metrics_test.py
Labels: :Metrics, enhancement

#1226 Fix docker release
  release-docker-test.sh
Labels: :Internal, cleanup
