Repository elastic/rally, pull requests merged in 2021-10, with the labels that each got.

#1348 Fix formatting commit in .git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: cleanup, :internal

#1342 Drop support for Elasticsearch 6.x metrics store
  docs/migrate.rst
  docs/versions.rst
  esrally/metrics.py
  esrally/resources/metrics-template.json
  esrally/resources/races-template.json
  esrally/resources/results-template.json
  tests/metrics_test.py
Labels: :Metrics, cleanup

#1347 remove formatter function from percentage diff evaluation
  esrally/reporter.py
  tests/reporter_test.py
Labels: bug, :Reporting, :internal

#1349 Allow running `make` commands with active virtualenv
  Makefile
Labels: :internal

#1351 Move version source of truth to esrally/_version.py
  .readthedocs.yml
  MANIFEST.in
  docker/Dockerfiles/Dockerfile-dev
  docs/conf.py
  esrally/__init__.py
  esrally/_version.py
  esrally/version.py
  release.sh
  setup.py
  version.txt
Labels: cleanup, :Packaging, :internal

#1352 Cleanup release files
  changelog.py
  create-notice.sh
  release.sh
Labels: cleanup, :internal

#1356 Stop mentioning removed "configure" command
  docs/developing.rst
Labels: :Docs, cleanup
