Repository elastic/rally, pull requests merged in 2021-11, with the labels that each got.

#1373 Revert "Retrieve master node using cat API"
  esrally/telemetry.py
  tests/telemetry_test.py
Labels: cleanup, :internal

#1368 Call the correct functions for `scroll-search` and `paginated-search` operations
  docs/track.rst
  esrally/driver/driver.py
  esrally/driver/runner.py
  esrally/track/params.py
  tests/driver/driver_test.py
  tests/driver/runner_test.py
  tests/track/params_test.py
Labels: bug, :Load Driver

#1378 Update chart-generator to remove license filter
  esrally/chart_generator.py
Labels: cleanup, :internal

#1383 Update adding tracks documentation
  docs/adding_tracks.rst
  docs/developing.rst
Labels: :Docs

#1385 Update chart-generator for release security by default
  esrally/chart_generator.py
Labels: cleanup, :internal

#1387 Switch to native pytest in tests/utils
  tests/utils/console_test.py
  tests/utils/convert_test.py
  tests/utils/git_test.py
  tests/utils/io_test.py
  tests/utils/jvm_test.py
  tests/utils/opts_test.py
  tests/utils/process_test.py
  tests/utils/repo_test.py
Labels: :misc, cleanup
