Repository elastic/rally, pull requests merged in 2021-07, with the labels that each got.

#1298 Use explicit config files for black and isort
  .isort.cfg
  Makefile
  black.toml
Labels: :misc, bug

#1285 Ensure exit code 130 is returned from SIGINT
  esrally/exceptions.py
  esrally/racecontrol.py
  esrally/rally.py
  esrally/utils/net.py
  it/distribution_test.py
Labels: enhancement

#1291 Drop relative-time-ms metric
  docs/metrics.rst
  docs/migrate.rst
  docs/recipes.rst
  esrally/metrics.py
  esrally/resources/metrics-template.json
  tests/metrics_test.py
Labels: :Metrics, breaking, enhancement

#1299 Add Makefile target to run all CI checks
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  Makefile
Labels: :Docs, enhancement

#1296 Add data streams telemetry device
  docs/telemetry.rst
  esrally/driver/driver.py
  esrally/telemetry.py
  tests/telemetry_test.py
Labels: :Telemetry, enhancement

#1304 Run integration tests with the default distro
  it/__init__.py
  it/distribution_test.py
  it/sources_test.py
Labels: :misc, enhancement

#1306 Fix deleting component/composable templates
  esrally/driver/runner.py
  esrally/track/params.py
  tests/driver/runner_test.py
  tests/track/params_test.py
Labels: bug

#1303 Add create and delete ILM policy runners
  docs/track.rst
  esrally/driver/runner.py
  esrally/track/track.py
  tests/driver/runner_test.py
Labels: :Load Driver, enhancement
