Repository elastic/rally, pull requests merged in 2021-01, with the labels that each got.

#1145 Fix punctuation
  docs/track.rst
Labels: :Docs, cleanup

#1143 Upgrade psutil dependency
  docs/developing.rst
  docs/install.rst
  setup.py
Labels: :Internal, enhancement

#1147 Don't require a name to register a track processor
  esrally/track/loader.py
Labels: :Track Management, bug

#1148 Make docs build stricter
  docs/Makefile
  setup.py
  tox.ini
Labels: :Docs, enhancement

#1151 Use regular dependency resolver in pip
  Makefile
  docker/Dockerfiles/Dockerfile-dev
  docker/Dockerfiles/Dockerfile-release
Labels: :Internal, cleanup

#1154 Allow to filter tasks by tag
  docs/command_line_reference.rst
  docs/track.rst
  esrally/track/loader.py
  esrally/track/track.py
  tests/track/loader_test.py
  tests/track/track_test.py
Labels: :Usability, enhancement

#1153 Only consider race id when loading a race
  esrally/metrics.py
Labels: :Metrics, :Usability, enhancement

#1155 Deprecate invoking Rally without a subcommand
  README.rst
  docs/adding_tracks.rst
  docs/cluster_management.rst
  docs/command_line_reference.rst
  docs/elasticsearch_plugins.rst
  docs/migrate.rst
  docs/pipelines.rst
  docs/quickstart.rst
  docs/race.rst
  docs/recipes.rst
  docs/telemetry.rst
  docs/tournament.rst
  docs/track.rst
  esrally/rally.py
  it/__init__.py
  it/docker_dev_image_test.py
Labels: :Usability, enhancement

#1146 Show mean throughput in command line report
  docs/quickstart.rst
  docs/race.rst
  docs/summary_report.rst
  esrally/reporter.py
Labels: :Reporting, enhancement

#1160 Include empty mean value in summary stats
  esrally/metrics.py
  tests/metrics_test.py
Labels: :Reporting, bug

#1159 Rally improve artifact download headers
  esrally/mechanic/supplier.py
  esrally/utils/net.py
  tests/utils/net_test.py
Labels: :Internal, enhancement

#1162 Log trace of uncaught exception in load generator
  esrally/driver/driver.py
Labels: :Usability, enhancement

#1163 Make some document properties extensible
  esrally/track/track.py
Labels: :Track Management, enhancement

#1157 Add support for assertions
  docs/command_line_reference.rst
  docs/recipes.rst
  docs/track.rst
  esrally/driver/driver.py
  esrally/driver/runner.py
  esrally/exceptions.py
  esrally/rally.py
  esrally/track/params.py
  it/__init__.py
  tests/driver/driver_test.py
  tests/driver/runner_test.py
  tests/mechanic/supplier_test.py
  tests/track/params_test.py
Labels: :Load Driver, enhancement
