Repository elastic/rally, pull requests merged in 2021-06, with the labels that each got.

#1274 Add example for raw-request
  docs/track.rst
Labels: :Docs, enhancement

#1275 Remove segment memory chart
  esrally/chart_generator.py
Labels: :Reporting, :internal

#1266 Support gradual ramp-up
  docs/track-ramp-up.png
  docs/track.rst
  esrally/driver/driver.py
  esrally/resources/track-schema.json
  esrally/track/loader.py
  esrally/track/track.py
  tests/driver/driver_test.py
  tests/track/loader_test.py
Labels: :Load Driver, enhancement

#1273 Re-introduce relative-time property
  docs/metrics.rst
  docs/migrate.rst
  docs/recipes.rst
  esrally/metrics.py
  esrally/resources/metrics-template.json
  tests/metrics_test.py
Labels: :Metrics, enhancement

#1277 Add chart support for observability queries
  esrally/chart_generator.py
Labels: :internal, enhancement

#1280 Add support for ml_processing_time chart
  esrally/chart_generator.py
Labels: :internal, enhancement

#1283 Set daemon attribute directly instead of using deprecated setter
  esrally/telemetry.py
Labels: :misc, cleanup

#1284 Ensure max_connections value is logged correctly
  esrally/async_connection.py
  esrally/utils/opts.py
  tests/utils/opts_test.py
Labels: :Load Driver, bug

#1287 Do not treat increase in transform processing/indexing/search time as improvement
  esrally/reporter.py
Labels: :Reporting, bug

#1293 fix download from s3/gs by moving http query parameter downstream
  esrally/utils/net.py
  tests/utils/net_test.py
Labels: :Benchmark Candidate Management, bug

#1292 Bump Python 3.8 version for dev and CI to 3.8.10
  .ci/variables.json
Labels: :Usability, enhancement

#1294 Fix composable templates runner
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: :Load Driver, bug

#1288 add transform-stats operation type
  docs/track.rst
  esrally/driver/runner.py
  esrally/track/track.py
  tests/driver/runner_test.py
Labels: :Load Driver, enhancement
