Repository elastic/rally, pull requests merged in 2021-02, with the labels that each got.

#1164 Update .pylintrc to remove exception
  .pylintrc
Labels: :Internal, cleanup

#1167 Clarify num of docs in corpora when action and metadata is used
  docs/track.rst
Labels: :Docs, enhancement

#1169 Document meta-data returned by operations
  docs/track.rst
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: :Docs, enhancement

#1172 Improve isolation in race control tests
  tests/racecontrol_test.py
Labels: :Internal, enhancement

#1168 Require unit for bulk operations
  docs/migrate.rst
  esrally/driver/runner.py
  tests/driver/driver_test.py
  tests/driver/runner_test.py
Labels: :Load Driver, cleanup

#1165 Fallback to closest minor branch for track/team repositories
  docs/car.rst
  docs/track.rst
  esrally/utils/repo.py
  esrally/utils/versions.py
  tests/utils/versions_test.py
Labels: :Usability, enhancement

#1174 Remove deprecated source pipelines
  docs/migrate.rst
  docs/pipelines.rst
  esrally/mechanic/supplier.py
  esrally/racecontrol.py
  it/sources_test.py
  tests/mechanic/supplier_test.py
  tests/metrics_test.py
  tests/racecontrol_test.py
Labels: :Benchmark Candidate Management, breaking, cleanup

#1093 Modify chart generator to support Kibana 7.x dashboards
  esrally/chart_generator.py
Labels: :Internal, enhancement

#1175 Always require a subcommand
  README.rst
  docs/command_line_reference.rst
  docs/elasticsearch_plugins.rst
  docs/migrate.rst
  docs/pipelines.rst
  docs/quickstart.rst
  docs/recipes.rst
  docs/telemetry.rst
  esrally/chart_generator.py
  esrally/driver/driver.py
  esrally/mechanic/launcher.py
  esrally/mechanic/mechanic.py
  esrally/mechanic/supplier.py
  esrally/mechanic/team.py
  esrally/metrics.py
  esrally/racecontrol.py
  esrally/rally.py
  esrally/reporter.py
  esrally/track/loader.py
  it/__init__.py
  it/generate_test.py
  it/resources/sample-race-config.json
  tests/mechanic/launcher_test.py
  tests/racecontrol_test.py
Labels: :Usability, breaking, enhancement

#1185 Fix installation docs after #1151
  docs/install.rst
Labels: :Docs, bug

#1192 Fix compare subcommand
  esrally/rally.py
Labels: :Reporting, bug

#1178 Always rely on source artifact caching
  esrally/mechanic/mechanic.py
  esrally/mechanic/supplier.py
  esrally/racecontrol.py
  esrally/rally.py
  tests/mechanic/supplier_test.py
Labels: :Usability, enhancement

#1181 Remove leftover from resolver cleanup
  tox.ini
Labels: :Internal, cleanup

#1177 Use operation name consistently in metrics samples
  esrally/driver/driver.py
  tests/driver/driver_test.py
Labels: :Load Driver, bug

#1194 update elasticsearch-py client to 7.10.1
  setup.py
Labels: :Load Driver

#1193 Add IT tests to test installation according to docs
  .ci/build.sh
  .ci/variables.json
  Makefile
  docs/conf.py
  docs/install.rst
  it/__init__.py
  it/distribution_test.py
  it/installation_test.py
  tox.ini
Labels: :Packaging, enhancement
