Repository elastic/rally, pull requests merged in 2021-05, with the labels that each got.

#1256 Adding threshold for node-stats warning at the beginning of the run
  esrally/telemetry.py
Labels: cleanup, enhancement

#1259 improvements to chart generator
  esrally/chart_generator.py
  esrally/rally.py
  it/generate_test.py
Labels: :internal, enhancement

#1263 Add pyenv shims to PATH
  .ci/build.sh
  Makefile
  docs/developing.rst
Labels: bug

#1265 Consolidate and improve track/team repo revision logic docs
  docs/car.rst
  docs/elasticsearch_plugins.rst
  docs/track.rst
Labels: :Docs, cleanup

#1264 Pass JAVA16_HOME in build
  tox.ini
Labels: :internal, enhancement

#1258 Record shard allocation
  docs/telemetry.rst
  esrally/driver/driver.py
  esrally/telemetry.py
  tests/telemetry_test.py
Labels: :Telemetry, enhancement

#1268 Fix error for shard-stats
  esrally/telemetry.py
Labels: :Telemetry, bug, enhancement

#1270 Include requests when installing google-resumable-media
  setup.py
Labels: :Packaging, bug

#1267 Consider new API calls in static response example
  docs/command_line_reference.rst
Labels: :Docs, bug
