Repository elastic/rally, pull requests merged in 2022-02, with the labels that each got.

#1423 Switch to native pytest in tests/track
  tests/track/loader_test.py
  tests/track/params_test.py
  tests/track/track_test.py
Labels: cleanup, :internal

#1429 Add ingest pipeline summary documentation
  docs/summary_report.rst
Labels: :Docs

#1425 Switch to first black version
  esrally/metrics.py
  esrally/reporter.py
  esrally/utils/net.py
  setup.py
  tests/metrics_test.py
  tests/telemetry_test.py
Labels: cleanup, :internal

#1426 Switch to native pytest in tests/mechanic
  tests/mechanic/java_resolver_test.py
  tests/mechanic/launcher_test.py
  tests/mechanic/mechanic_test.py
  tests/mechanic/provisioner_test.py
  tests/mechanic/supplier_test.py
  tests/mechanic/team_test.py
Labels: cleanup, :internal

#1433 minor change to docs
  docs/track.rst
Labels: :Docs, :internal

#1412 Parallelize on corpora basis in bulk task clients
  esrally/track/params.py
  tests/track/params_test.py
Labels: enhancement, feedback needed

#1440 Fix build by downgrading markupsafe
  setup.py
Labels: bug, :Packaging

#1437 Support csv values as JSON
  docs/command_line_reference.rst
  docs/migrate.rst
  esrally/utils/opts.py
  tests/utils/opts_test.py
Labels: enhancement, :Usability

#1444 Add Ingest Processor Line Chart to Chart Generator
  esrally/chart_generator.py
Labels: enhancement, :Metrics, :internal

#1439 Switch to native pytest in tests/driver
  setup.cfg
  setup.py
  tests/driver/driver_test.py
  tests/driver/runner_test.py
  tests/driver/scheduler_test.py
Labels: cleanup, :internal

#1443 Finish migration to native pytest
  benchmarks/driver/parsing_test.py
  tests/client_test.py
  tests/config_test.py
  tests/metrics_test.py
  tests/reporter_test.py
  tests/telemetry_test.py
  tests/test_async_connection.py
  tests/time_test.py
  tests/track/loader_test.py
Labels: cleanup, :internal

#1445 Fix wait-for-snapshot-create action
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: bug
