Repository elastic/rally, pull requests merged in 2022-07, with the labels that each got.

#1539 Correctly log how long it took to close transports
  esrally/driver/driver.py
Labels: bug, :misc, cleanup

#1497 Remove Elasticsearch 6.3 logic
  docs/car.rst
  docs/elasticsearch_plugins.rst
  esrally/driver/driver.py
  esrally/mechanic/provisioner.py
  esrally/telemetry.py
  tests/mechanic/provisioner_test.py
  tests/telemetry_test.py
Labels: cleanup, :internal

#1476 Surface ES startup errors to the Rally CLI console
  esrally/mechanic/launcher.py
  tests/driver/runner_test.py
  tests/mechanic/launcher_test.py
Labels: enhancement

#1547 Fix one remaining default flavor
  esrally/telemetry.py
Labels: bug, :Telemetry

#1550 Revert "Surface ES startup errors to the Rally CLI console (#1476)"
  esrally/mechanic/launcher.py
  tests/driver/runner_test.py
  tests/mechanic/launcher_test.py
Labels: bug
