Repository elastic/rally, pull requests merged in 2022-03, with the labels that each got.

#1447 Stop leading users away from finding errors in docs
  docs/recipes.rst
Labels: :Docs

#1438 Introduce `sql` operation type
  docs/track.rst
  esrally/driver/runner.py
  esrally/track/track.py
  tests/driver/runner_test.py
Labels: enhancement

#1451 Run pylint like the other Python tools
  Makefile
Labels: cleanup, :internal

#1461 Add 'root' attribute to Track class
  esrally/track/loader.py
  esrally/track/track.py
Labels: enhancement

#1463 Support refresh-timeout (and other kwargs) for Refresh
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: bug

#1465 re sort where disk usage charts land in dashboard
  esrally/chart_generator.py
Labels: :internal

#1467 Make online detection more resilient
  esrally/utils/net.py
Labels: enhancement, :Usability

#1449 Add "revisions" chart type to chart generator
  esrally/chart_generator.py
  setup.py
Labels: enhancement

#1469 Set enable_cleanup_closed by default
  docs/command_line_reference.rst
  esrally/async_connection.py
  tests/client_test.py
  tests/driver/runner_test.py
Labels: bug

#1405 Add track dependency support
  docs/track.rst
  esrally/driver/driver.py
  esrally/paths.py
  esrally/racecontrol.py
  esrally/resources/track-schema.json
  esrally/track/loader.py
  esrally/track/track.py
  esrally/utils/modules.py
  it/dependencies_test.py
  it/resources/track_with_dependency/track.json
  it/resources/track_with_dependency/track.py
Labels: enhancement, :Config, highlight
