Repository elastic/rally, pull requests merged in 2022-06, with the labels that each got.

#1496 Fix use_ssl: True on Python 3.10 (second try)
  Makefile
  esrally/client.py
  setup.py
  tests/client_test.py
Labels: bug

#1507 Remove unused analyze.py script
  scripts/analyze.py
Labels: cleanup, :internal

#1512 Prepare switch to Elasticsearch Python client 8.2.0
  esrally/client.py
  esrally/driver/runner.py
  esrally/metrics.py
  esrally/telemetry.py
  esrally/tracker/index.py
  tests/driver/driver_test.py
  tests/driver/runner_test.py
  tests/telemetry_test.py
Labels: cleanup, :internal

#1513 Move all ES client-related code into its own package.
  esrally/client/__init__.py
  esrally/client/asynchronous.py
  esrally/client/context.py
  esrally/client/factory.py
  esrally/client/synchronous.py
  tests/client/__init__.py
  tests/client/asynchronous_test.py
  tests/client/factory_test.py
Labels: cleanup, :internal

#1515 Replace os.system with subprocess.call
  esrally/utils/process.py
  it/__init__.py
Labels: cleanup, :internal

#1478 Allow configuring Elasticsearch cluster name
  docs/command_line_reference.rst
  esrally/mechanic/provisioner.py
  esrally/rally.py
  it/__init__.py
  tests/mechanic/provisioner_test.py
Labels: enhancement

#1518 Relax target-hosts check for multi clusters
  esrally/rally.py
  it/distribution_test.py
Labels: bug

#1521 Retry incomplete HTTP downloads
  esrally/utils/net.py
Labels: bug, :Usability

#1516 Create an ES client per simulated client instead of per worker.
  esrally/driver/driver.py
Labels: :Load Driver

#1529 Make git.clone remote kwarg-only
  esrally/mechanic/supplier.py
  esrally/utils/git.py
  esrally/utils/repo.py
  tests/mechanic/supplier_test.py
  tests/utils/git_test.py
  tests/utils/repo_test.py
Labels: cleanup, :internal

#1526 Add runner for paging through composite aggregations
  docs/track.rst
  esrally/chart_generator.py
  esrally/driver/runner.py
  esrally/track/params.py
  esrally/track/track.py
  tests/driver/runner_test.py
Labels: enhancement, :Track Management

#1530 Add OS mem stats to node-stats telemetry device
  docs/telemetry.rst
  esrally/telemetry.py
  tests/telemetry_test.py
Labels: enhancement, :Metrics, :Usability, :Telemetry, :Docs

#1525 docs/conf.py: rename master_doc to root_doc
  docs/conf.py
Labels: cleanup, :internal

#1532 Use main branch of Elasticsearch for source builds
  README.rst
  docs/car.rst
  docs/command_line_reference.rst
  docs/developing.rst
  docs/elasticsearch_plugins.rst
  docs/migrate.rst
  docs/track.rst
  esrally/mechanic/supplier.py
  esrally/racecontrol.py
  esrally/rally.py
  esrally/track/loader.py
  tests/mechanic/supplier_test.py
Labels: enhancement, highlight
