Repository elastic/rally, pull requests merged in 2022-08, with the labels that each got.

#1555 Add an integration test for static responses.
  it/resources/static-responses.json
  it/static_responses_test.py
Labels: tech debt

#1557 Remove duplicate property descriptions from corpora docs
  docs/track.rst
Labels: :Docs

#1553 Run unit and integration tests in separate tox environments
  Makefile
  tox.ini
Labels: :misc, tech debt

#1542 Add new wait-for-current-snapshots-create operation
  docs/track.rst
  esrally/driver/runner.py
  esrally/track/track.py
  tests/driver/runner_test.py
Labels: enhancement, :Track Management

#1548 Move most packaging metadata to pyproject.toml
  .ci/variables.json
  docker/Dockerfiles/Dockerfile-dev
  pyproject.toml
  setup.cfg
  setup.py
Labels: :internal, tech debt

#1559 Install Rally in PEP 517 mode
  .ci/variables.json
  Makefile
  docker/Dockerfiles/Dockerfile-dev
  docker/Dockerfiles/Dockerfile-release
  run.sh
  tox.ini
Labels: bug, tech debt

#1551 Switch from setuptools to hatchling
  .ci/variables.json
  MANIFEST.in
  Makefile
  docker/Dockerfiles/Dockerfile-dev
  docker/Dockerfiles/Dockerfile-release
  docs/create_scheduler_plot.py
  pyproject.toml
  release.sh
  setup.py
Labels: cleanup, :internal, tech debt

#1561 Migrate Jenkins job definitions and parallelize PR checks
  .ci/build.sh
  .ci/jobs/defaults.yml
  .ci/jobs/periodic-it310.yml
  .ci/jobs/periodic-it38.yml
  .ci/jobs/periodic-precommit.yml
  .ci/jobs/periodic.yml
  .ci/jobs/pull-request-it310.yml
  .ci/jobs/pull-request-it38.yml
  .ci/jobs/pull-request-precommit.yml
  .ci/jobs/push-it310.yml
  .ci/jobs/push-it38.yml
  .ci/jobs/push-precommit.yml
  .ci/jobs/push.yml
  .ci/jobs/release-docker.yml
  .ci/templates/it.yml
  .ci/templates/periodic.yml
  .ci/templates/precommit.yml
  .ci/templates/pull-request-it.yml
  .ci/templates/push.yml
  .ci/views/views.yml
  Makefile
Labels: :internal, tech debt

#1554 Link to the 7.14.0 ES Python client docs.
  docs/command_line_reference.rst
  docs/conf.py
Labels: :Docs

#1563 Fix multi-cluster attribute check for wrapped runners
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: bug, enhancement

#1546 Run lint with pre-commit
  .pre-commit-config.yaml
  Makefile
  docs/developing.rst
  pyproject.toml
Labels: cleanup

#1567 Bump develop dependencies
  docs/conf.py
  pyproject.toml
Labels: tech debt

#1565 Fix `make lint` on Python 3.10
  .pylintrc
  benchmarks/track/bulk_params_test.py
  esrally/client/factory.py
  esrally/driver/runner.py
  esrally/mechanic/mechanic.py
  esrally/mechanic/supplier.py
  esrally/mechanic/team.py
  esrally/metrics.py
  esrally/rally.py
  esrally/telemetry.py
  esrally/track/loader.py
  esrally/track/params.py
  esrally/utils/io.py
  esrally/utils/repo.py
  pyproject.toml
  tests/driver/driver_test.py
  tests/driver/runner_test.py
  tests/mechanic/java_resolver_test.py
  tests/mechanic/mechanic_test.py
  tests/mechanic/provisioner_test.py
  tests/mechanic/supplier_test.py
  tests/metrics_test.py
  tests/racecontrol_test.py
  tests/telemetry_test.py
  tests/track/loader_test.py
  tests/utils/console_test.py
  tests/utils/git_test.py
  tests/utils/io_test.py
  tests/utils/jvm_test.py
  tests/utils/net_test.py
  tests/utils/process_test.py
  tests/utils/repo_test.py
  tests/utils/versions_test.py
Labels: tech debt

#1498 Bump upper tested version to 8.4.0
  it/__init__.py
  it/distribution_test.py
Labels: tech debt
