Repository elastic/rally, pull requests merged in 2022-12, with the labels that each got.

#1633 Remove internal chart generator
  esrally/chart_generator.py
  esrally/driver/driver.py
  esrally/rally.py
  it/generate_test.py
  it/resources/sample-race-config.json
Labels: cleanup, :internal

#1638 Don't use --short when retrieving revisions from git
  esrally/utils/git.py
Labels: bug, :Usability

#1641 Docs: add jq to the software packages list
  docs/developing.rst
Labels: :Docs

#1640 Pass plugin-params also for modules
  esrally/mechanic/provisioner.py
  tests/mechanic/provisioner_test.py
Labels: bug, :Benchmark Candidate Management
