Repository elastic/rally, pull requests merged in 2022-09, with the labels that each got.

#1569 Remove release benchmarks
  esrally/chart_generator.py
  esrally/rally.py
  it/generate_test.py
Labels: tech debt

#1571 Stop trying to test Elasticsearch 6.8.0 on ARM
  it/__init__.py
Labels: tech debt

#1570 Use Docker for Elasticsearch source builds
  esrally/mechanic/supplier.py
  esrally/rally.py
  it/sources_test.py
  pyproject.toml
  tests/mechanic/supplier_test.py
Labels: enhancement, :Config, :internal

#1578 Correctly retry HTTP downloads after incomplete reads
  esrally/utils/net.py
  tests/utils/net_test.py
Labels: bug, :Load Driver

#1580 Remove buggy indices.exists() calls from code
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: bug

#1576 Add build subcommand
  docs/command_line_reference.rst
  esrally/mechanic/__init__.py
  esrally/mechanic/mechanic.py
  esrally/mechanic/supplier.py
  esrally/rally.py
  it/sources_test.py
Labels: enhancement

#1574 Include a new downsampling operation
  docs/track.rst
  esrally/driver/runner.py
  esrally/track/params.py
  esrally/track/track.py
  tests/driver/runner_test.py
  tests/track/params_test.py
Labels: enhancement, highlight

#1579 Use narrower exception to avoid pylint ignore
  esrally/utils/net.py
Labels: cleanup

#1584 Add support for assertions on raw requests
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: enhancement

#1586 Fix supplier tests for aarch64
  tests/mechanic/supplier_test.py
Labels: bug

#1590 Revert "Add support for assertions on raw requests"
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: bug

#1587 Refactor `pull_revision` to `pull`
  docs/command_line_reference.rst
  docs/configuration.rst
  esrally/mechanic/supplier.py
  esrally/utils/git.py
  tests/mechanic/supplier_test.py
  tests/utils/git_test.py
Labels: bug
