Repository elastic/rally, pull requests merged in 2022-05, with the labels that each got.

#1479 Bump boto3 to 1.18.46
  setup.py
Labels: :Packaging

#1482 Allow compare to continue for missing disk usage stats
  esrally/reporter.py
Labels: bug

#1489 Not every composable template has a top-level `template`
  esrally/track/params.py
  tests/track/params_test.py
Labels: bug

#1493 Fix use_ssl: True on Python 3.10
  Makefile
  esrally/client.py
  setup.py
  tests/client_test.py
Labels: bug

#1488 Replace run_async with pytest.mark.asyncio
  tests/__init__.py
  tests/client_test.py
  tests/driver/driver_test.py
  tests/driver/runner_test.py
Labels: cleanup, :internal

#1501 metrics.rst: minor formatting correction
  docs/metrics.rst
Labels: :Docs
