Repository elastic/rally, pull requests merged in 2023-05, with the labels that each got.

#1710 Actually use client returned from '.options()'
  esrally/driver/runner.py
  tests/driver/driver_test.py
  tests/driver/runner_test.py
Labels: bug, :Load Driver

#1712 Downgrade Python 3.11 to work around aiohttp bug
  .ci/variables.json
Labels: bug

#1703 Improve exception handling for metrics store errors
  esrally/metrics.py
  tests/metrics_test.py
Labels: bug, :Metrics

#1701 Stop asserting time spent in AsyncProfiler
  tests/driver/driver_test.py
Labels: tech debt, :ci

#1715 Show Rally builds in Buildkite default view
  catalog-info.yaml
Labels: cleanup, :ci

#1716 Prepare release Docker pipeline
  .buildkite/release-docker/pipeline.yml
  catalog-info.yaml
Labels: enhancement, :ci

#1719 Bump up minimum Python version
  .ci/variables.json
Labels: bug, :Usability
