Repository elastic/rally, pull requests merged in 2023-03, with the labels that each got.

#1675 Declare Buildkite pipelines
  catalog-info.yaml
Labels: tech debt, :ci

#1677 Define Buildkite IT pipeline file
  catalog-info.yaml
Labels: tech debt, :ci

#1676 Sync main branch
  .github/workflows/sync-main-branch.yml
Labels: tech debt, :ci

#1680 Revert "Add a variable in the provisioner for the seed node count"
  esrally/mechanic/provisioner.py
  tests/mechanic/provisioner_test.py
Labels: :internal, tech debt

#1669 Upgrade ES Client to 8.x
  docs/command_line_reference.rst
  docs/migrate.rst
  esrally/client/asynchronous.py
  esrally/client/common.py
  esrally/client/factory.py
  esrally/client/synchronous.py
  esrally/driver/driver.py
  esrally/driver/runner.py
  esrally/log.py
  esrally/metrics.py
  esrally/resources/logging.json
  esrally/telemetry.py
  esrally/tracker/tracker.py
  esrally/utils/opts.py
  it/__init__.py
  it/esrallyd_test.py
  it/proxy_test.py
  pyproject.toml
  tests/client/common_test.py
  tests/client/factory_test.py
  tests/driver/driver_test.py
  tests/driver/runner_test.py
  tests/log_test.py
  tests/metrics_test.py
  tests/telemetry_test.py
  tests/tracker/corpus_test.py
  tests/utils/opts_test.py
  tests/utils/resources/target_hosts_1.json
Labels: enhancement, :Docs, :Load Driver, :Config, highlight, discuss

#1679 Migrate from Jenkins to Buildkite and GitHub Actions
  .buildkite/it/pipeline.yml
  .buildkite/it/run.sh
  .buildkite/pull-requests.json
  .ci/build.sh
  .ci/jobs/defaults.yml
  .ci/jobs/periodic-it310.yml
  .ci/jobs/periodic-it38.yml
  .ci/jobs/periodic.yml
  .ci/jobs/pull-request-it310.yml
  .ci/jobs/pull-request-it38.yml
  .ci/jobs/pull-request-rally-tracks-compat.yml
  .ci/jobs/push-it310.yml
  .ci/jobs/push-it38.yml
  .ci/jobs/push.yml
  .ci/templates/it.yml
  .ci/templates/periodic.yml
  .ci/templates/pull-request-it.yml
  .ci/templates/push.yml
  .github/workflows/ci.yml
  Makefile
  noxfile.py
  tox.ini
Labels: :internal, :ci

#1663 Add operating system cgroup stats to node-stats telemetry
  docs/telemetry.rst
  esrally/telemetry.py
  tests/telemetry_test.py
Labels: enhancement

#1684 Revert "Sync main branch (#1676)"
  .github/workflows/sync-main-branch.yml
Labels: tech debt, :ci

#1683 Upgrade Elasticsearch client to 8.6.1
  docs/command_line_reference.rst
  docs/migrate.rst
  esrally/client/asynchronous.py
  esrally/client/common.py
  esrally/client/factory.py
  esrally/client/synchronous.py
  esrally/driver/driver.py
  esrally/driver/runner.py
  esrally/log.py
  esrally/metrics.py
  esrally/resources/logging.json
  esrally/telemetry.py
  esrally/tracker/tracker.py
  esrally/utils/opts.py
  it/__init__.py
  it/esrallyd_test.py
  it/proxy_test.py
  pyproject.toml
  tests/client/common_test.py
  tests/client/factory_test.py
  tests/driver/driver_test.py
  tests/driver/runner_test.py
  tests/log_test.py
  tests/metrics_test.py
  tests/telemetry_test.py
  tests/tracker/corpus_test.py
  tests/utils/opts_test.py
  tests/utils/resources/target_hosts_1.json
Labels: enhancement, :Docs, :Load Driver, :Config, highlight

#1686 Use simply expanded vars assignment in Makefile
  Makefile
Labels: bug, :internal

#1690 Use correct params for create component template
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: bug, :Load Driver

#1692 Allow to delete indices related to index templates
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: bug, :Load Driver

#1681 Exclude closed pull requests from changelog
  CHANGELOG.md
  changelog.py
Labels: bug, :internal

#1685 Add support for Python 3.11
  .buildkite/it/pipeline.yml
  .buildkite/it/run.sh
  .ci/variables.json
  .github/workflows/ci.yml
  .pylintrc
  .readthedocs.yaml
  Makefile
  esrally/driver/driver.py
  esrally/mechanic/supplier.py
  esrally/utils/net.py
  noxfile.py
  pyproject.toml
  tests/driver/driver_test.py
  tests/track/loader_test.py
Labels: tech debt, :ci

#1691 Ignore HTTP 404 consistently in runners
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: bug, :Load Driver
