Repository elastic/rally, pull requests merged in 2023-06, with the labels that each got.

#1722 Increase 'mapping.total_fields.limit' to '2000'
  esrally/resources/metrics-template.json
Labels: bug, :Metrics, :Telemetry

#1725 Make async context manager synchronous
  esrally/client/context.py
  esrally/driver/driver.py
  esrally/driver/runner.py
  tests/client/factory_test.py
  tests/driver/driver_test.py
  tests/driver/runner_test.py
Labels: :internal, tech debt

#1727 Allow configuring logging to use local time
  docs/configuration.rst
  esrally/log.py
  tests/log_test.py
Labels: enhancement

#1728 Revert "Upgrade Jinja2 to version 3.1.2"
  pyproject.toml
Labels: bug, :internal

#1732 Fix license URLs in create notice script
  create-notice.sh
Labels: bug, :internal

#1729 Bump Python to 3.11.4
  .ci/variables.json
Labels: bug, :internal

#1734 Add daily schedule to Buildkite IT pipeline
  catalog-info.yaml
Labels: :internal, :ci

#1742 Fix rally-it pipeline slug
  .buildkite/pull-requests.json
Labels: :internal, :ci

#1733 Run all tests on release
  Makefile
Labels: bug, :internal
