Repository elastic/rally, pull requests merged in 2023-01, with the labels that each got.

#1643 Skip response parsing for raw requests
  esrally/driver/runner.py
Labels: enhancement, :Load Driver

#1649 Allow specifying installation id
  esrally/rally.py
Labels: enhancement, :Usability, :Config

#1647 Add a variable in the provisioner for the seed node count
  esrally/mechanic/provisioner.py
  tests/mechanic/provisioner_test.py
Labels: bug

#1651 Stop checking for madvise availability
  esrally/utils/io.py
Labels: tech debt

#1648 Fix broken links on the command line reference docs
  docs/command_line_reference.rst
Labels: bug, :Docs

#1654 Add role metadata to node-stats telemetry device
  esrally/telemetry.py
  tests/telemetry_test.py
Labels: enhancement, :Usability, :Telemetry

#1656 Rename from_is8601 to from_iso8601
  esrally/metrics.py
  esrally/time.py
Labels: tech debt

#1657 Cleanup params_test.py file
  tests/track/params_test.py
Labels: tech debt

#1613 Document Track Processor Interface
  docs/adding_tracks.rst
  docs/advanced.rst
  docs/configuration.rst
  docs/index.rst
  esrally/track/loader.py
Labels: :Docs
