Repository elastic/rally, pull requests merged in 2023-11, with the labels that each got.

#1797 Document Rally use with Elastic Serverless
  docs/advanced.rst
  docs/developing.rst
  docs/index.rst
  docs/serverless.rst
  docs/telemetry.rst
  docs/track.rst
Labels: :Docs

#1799 Checkout tag on Docker release
  .buildkite/release-docker/run.sh
Labels: :ci

#1803 Skip metrics that are missing in either contender or baseline
  esrally/reporter.py
Labels: enhancement

#1801 Raise error if 'policy' field missing in create-ilm operation body
  esrally/driver/runner.py
Labels: enhancement, :Load Driver

#1806 Pin transitive dep 'aiohttp==3.8.6'
  pyproject.toml
Labels: bug, :Load Driver, dependencies

#1808 Remove 'aiohttp' pin
  pyproject.toml
Labels: :Load Driver, :Packaging, dependencies
