Repository elastic/rally, pull requests merged in 2023-04, with the labels that each got.

#1696 Archive Rally logs in rally-tracks-compat job
  .github/workflows/ci.yml
Labels: tech debt, :ci

#1698 Update progress after GCS download finished
  esrally/utils/net.py
Labels: bug, :Track Management

#1687 Propagate request start/end lazily
  esrally/client/context.py
  tests/client/factory_test.py
Labels: bug, :Load Driver

#1705 Refactor some runners to set transport level options
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: bug

#1708 Use correct reference for Python 3.11
  .ci/variables.json
Labels: bug, :internal

#1702 Include 'refresh' and 'flush' stats by default when using 'node-stats-include-indices
  esrally/telemetry.py
  tests/telemetry_test.py
Labels: enhancement, :Telemetry

#1706 Allow specifying branch together with timestamp in revision
  docs/command_line_reference.rst
  esrally/mechanic/supplier.py
  esrally/rally.py
  tests/mechanic/supplier_test.py
Labels: enhancement, :Benchmark Candidate Management

#1707 Evenly distribute client connections across hosts
  esrally/client/asynchronous.py
  esrally/client/factory.py
  esrally/driver/driver.py
  tests/client/asynchronous_test.py
Labels: bug, enhancement, :Load Driver
