Repository elastic/rally, pull requests merged in 2023-09, with the labels that each got.

#1776 Wait DNS for 15 minutes in serverless test
  it_serverless/serverless_test.py
Labels: :ci

#1778 Support API key authentication
  docs/command_line_reference.rst
  esrally/client/factory.py
Labels: enhancement

#1779 Simplify ClusterEnvironmentInfo telemetry device
  esrally/telemetry.py
  tests/telemetry_test.py
Labels: tech debt

#1782 Add public user to serverless test
  it_serverless/__init__.py
  it_serverless/conftest.py
  it_serverless/serverless_test.py
  pyproject.toml
Labels: :ci

#1784 Fix crash on too many consecutive errors
  pyproject.toml
Labels: bug

#1786 Add support for zstd-compression
  create-notice.sh
  docs/install.rst
  docs/track.rst
  esrally/utils/io.py
  pyproject.toml
  tests/utils/io_test.py
  tests/utils/resources/test.txt.zst
Labels: enhancement, :Track Management
