Repository elastic/rally, pull requests merged in 2024-05, with the labels that each got.

#1846 Update create track
  docs/adding_tracks.rst
  docs/command_line_reference.rst
  esrally/rally.py
  esrally/resources/challenges.json.j2
  esrally/resources/operations.json.j2
  esrally/resources/track.json.j2
  esrally/tracker/corpus.py
  esrally/tracker/tracker.py
  esrally/types.py
Labels: enhancement

#1849 Remove esql version
  docs/track.rst
  esrally/driver/runner.py
  tests/driver/runner_test.py
Labels: cleanup

#1838 [it tests] Upload logs as buildkite artifact even on failure
  .buildkite/it/run.sh
  .buildkite/it/run_serverless.sh
Labels: enhancement, :ci
