Repository elastic/rally, pull requests merged in 2025-02, with the labels that each got.

#1909 Add check if headers is not None before treating it like a dict
  esrally/client/common.py
Labels: enhancement

#1915 Soften pyenv recommendation
  docs/install.rst
Labels: :Docs

#1653 Upgrade thespian to 4.0.0 to fix hang on macOS
  pyproject.toml
Labels: bug
